version: '3.7'
services:
  php:
    image: $CI_REGISTRY_IMAGE/php/test
    volumes:
      - ./logs:/code/storage/logs
    build:
      context: .
      dockerfile: .docker/php/Dockerfile.test
      cache_from:
        - $CI_REGISTRY_IMAGE/php/test
    environment:
      APP_NAME: Restor'It
      APP_ENV: local
      APP_KEY: base64:lzOSGM/hVNEDISJBDmfUL3CclEWA7PVGh4VrARvWGpk=
      APP_DEBUG: 'true'
      APP_URL: http://localhost:8000

      DB_CONNECTION: sqlite
      DB_DATABASE: ':memory:'
      LOG_DRIVER: single
      MAIL_DRIVER: log
      MAIL_FROM_ADDRESS: noreply@restorit.fr
      MAIL_FROM_NAME: Restor'It

      AWS_ACCESS_KEY_ID: AKIAII47E4VKBUT2K3WA
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: eu-west-3
      AWS_BUCKET: storage-dev.restorit.fr

      JWT_SECRET: vXsEelOUz60Jmzc82wibGkKoywjmbXaT357dUOrpDfPUbXjCdKObxysfgOaRyaQ3
      JWT_TTL: 10080
